### ISSUE TITLE
Issue with moving items to and from inventory

### ISSUE THREAD

**Issue by Arkosee** [MaDHouSe79/mh-inventory#1]
Hey, just installed mh-inventory, and the below is now an error I'm receiving upon dropping items and also when trying to pick up items. Basically the items won't move from one inventory or the other (you can move them but when closing the inventory and opening it, they'll be back where they were originally)

![Screenshot 2023-10-15 081943](https://github.com/MaDHouSe79/mh-inventory/assets/105973488/87b36074-21de-4fc3-97a3-a3adfe9c51c2)

**Comment by MaDHouSe79** [comment]
i checnge it, copy the server only, cause i obly change that part for you ;)

**Comment by Arkosee** [comment]
Seems to have fixed the top qb-core issue, but I'm stilling receiving the second one; Which is when pulling items from the "Dropped" inventory section

![Screenshot 2023-10-15 085054](https://github.com/MaDHouSe79/mh-inventory/assets/105973488/21e13968-1304-4490-ad3f-370c33c193f0)

**Comment by MaDHouSe79** [comment]
i just change it again, see if this works for you

**Comment by Arkosee** [comment]
Awesome, that seems to have fixed it :)
