### ISSUE TITLE
This ones going to be interesting (lol)

### ISSUE THREAD

**Issue by Arkosee** [MaDHouSe79/mh-inventory#2]
Soo.. I use your cashasitem resource.. Works awesome, I love it! I also made a "fork" I guess so we could have a "blackmoney" item for our blackmoney type we use.

Here is where it begins to get interesting with the inventory though, so everything works as usual EXCEPT the blackmoney, dropping or moving it outside of your own inventory does not work, it just stays there and wigs out.. Now.. I think I've figured out why.. 

This is because the inventory calls for `mh-cashasitem:server:updateCash` a bunch to obviously update cash as it drops/moves etc..

Now with the blackmoney fork I made, I obviously had to renamed the resource since we couldn't have 2 of the same resource name running at the same time working with different money types.. So I called it `mh-blackmoneyasitem`

I'm 100% certain because it's called like it is, there needs to be a bunch of `mh-blackmoneyasitem:server:updateCash` events now made correct?

My "issue" is that I'm not sure/skilled enough to know how exactly to add them in alongside the normal `mh-cashasitem:server:updateCash` events (since those events need to be doubled up on but with the new name I guess?) so they can work side by side..

My question is; Would you be willing to help? xD

**Comment by MaDHouSe79** [comment]
the easy way to do this in go in your qb-core config and make a other money type,
```lua
QBConfig.Money.MoneyTypes = { cash = 500, bank = 5000, crypto = 0 } -- type = startamount - Add or remove money types for your server (for ex. blackmoney = 0), remember once added it will not be removed from the database!
```

here you can make like this:
```lua
QBConfig.Money.MoneyTypes = { cash = 500, bank = 5000, crypto = 0, blackmoney = 0 }
```

**Comment by Arkosee** [comment]
> the easy way to do this is go in your qb-core config and make a other money type,
> 
> ```lua
> QBConfig.Money.MoneyTypes = { cash = 500, bank = 5000, crypto = 0 } -- type = startamount - Add or remove money types for your server (for ex. blackmoney = 0), remember once added it will not be removed from the database!
> ```
> 
> here you can make like this:
> 
> ```lua
> QBConfig.Money.MoneyTypes = { cash = 500, bank = 5000, crypto = 0, blackmoney = 0 }
> ```
> 
> with this you only have to use 1 script ;) not 2 like you do ;)
> 
> i may have to change 1 thing in the script to make this work.

Yes this was already done, the issue we ran into though is that without the "forked" blackmoneyasitem,  when we sold drugs/received the blackmoney from places, it didn't show up in your inventory as an item since nothing was converting "blackmoney" to an item, it was only converting "cash".

Which is why I need to create the fork, but then we ran into the whole issue above with the events being needed in the inventory xD (it's been a long day of testing lol)

**Comment by MaDHouSe79** [comment]
can you send my you script? so i can make it 1?

**Comment by Arkosee** [comment]
Here is the version I made.. I'm sure there are issue with it as I'm learning, so please do let me know if I messed up anywhere :)

[mh-blackmoneyasitem.zip](https://github.com/MaDHouSe79/mh-inventory/files/12908888/mh-blackmoneyasitem.zip)

**Comment by MaDHouSe79** [comment]
Ok the cashasitem script you don' t need this for the blackmoney,
what you need to do is, replace all marked_money for the blackmoney item
cause blackmoney is not realy like cash, it' s just a item but not like cash, my cash as item is made to work with cash only.
why i did this is becasue all other types of money are already items so i don't think we have to change the script,
what you need to do is this,
you need to replace every code that give you marked_money and change that to give AddItem("blackmoney", 10, nil)
as example, in this case you get it in your inventory. but you can't pay with it like the cash because you need to was it before you can use it.

Change this
```lua
local info = {
    worth = math.random(2300, 3200)
}
ply.Functions.AddItem('markedbills', math.random(2,3), false, info)
TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['markedbills'], "add")
```
into this
```lua
local itemAmount = math.random(2, 5)
ply.Functions.AddItem("blackmoney", itemAmount)
```

**Comment by Arkosee** [comment]
> Ok the cashasitem script you don' t need this for the blackmoney, what you need to do is, replace all marked_money for the blackmoney item cause blackmoney is not realy like cash, it' s just a item but not like cash, my cash as item is made to work with cash only. why i did this is becasue all other types of money are already items so i don't think we have to change the script, what you need to do is this, you need to replace every code that give you marked_money and change that to give AddItem("blackmoney", 10, nil) as example, in this case you get it in your inventory. but you can't pay with it like the cash because you need to was it before you can use it.
> 
> Change this
> 
> ```lua
> local info = {
>     worth = math.random(2300, 3200)
> }
> ply.Functions.AddItem('markedbills', math.random(2,3), false, info)
> TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['markedbills'], "add")
> ```
> 
> into this
> 
> ```lua
> local itemAmount = math.random(2, 5)
> ply.Functions.AddItem("blackmoney", itemAmount)
> ```
> 
> The point is that cash and dirty money are not linked to the same money system, if you have a script that you want to use blackmoney just give it to my and i show you what you need to change ;)



So the way _blackmoney_ works atm in our server is exactly like cash I believe.

- We have the `MoneyType` in the qb-core config;

- We receive it as `Player.Functions.AddMoney("blackmoney", price)` for drug selling currently (there are other places we need to change from markedbills which I can send through)

- We have it has something you can use at our blackmarket via;
```lua
RegisterNetEvent('qb-blackmarket:Buyitems', function (cd)
    local src = source 
	local Player = QBCore.Functions.GetPlayer(src)
    local cash = Player.Functions.GetMoney('blackmoney')
    item = cd.item
    price = cd.price
    if Player.Functions.AddItem(item, 1) and cash >= price then
        Player.Functions.RemoveMoney('blackmoney', price)
        Player.Functions.AddItem(item, 1)
        TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items[item], "add")
    else
        TriggerClientEvent('QBCore:Notify', src, "You Don't Have Enough money", 'error')
    end
end)
```
- Plus with it as an "Item" in the inventory, it allows criminals to steal it from other criminals etc


The only real issue we have is that it isn't working correctly on the inventory side which I figured was down to those events not being made for the fork version I had made

**Comment by MaDHouSe79** [comment]
maby this works?

```lua
RegisterNetEvent('qb-blackmarket:Buyitems', function (cd)
    local src = source 
    local Player = QBCore.Functions.GetPlayer(src)
    local blackmoney = exports['qb-inventory']:GetItemByName(src, "blackmoney")
    if blackmoney.amount >= cd.price then
        local amount = 1
        Player.Functions.RemoveItem('blackmoney', cd.price)
        Player.Functions.AddItem(cd.item, amount)
        TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items[cd.item], "add", amount)
    else
        TriggerClientEvent('QBCore:Notify', src, "You Don't Have Enough money", 'error')
    end
end)
```

**Comment by MaDHouSe79** [comment]
or do this
yours
```lua
RegisterNetEvent('qb-blackmarket:Buyitems', function (cd)
    TriggerEvent('mh-cashasitem:server:buyitem', cd)
end)
```
mine
```lua
RegisterNetEvent('mh-cashasitem:server:buyitem', function (data)
    local src = source 
    local Player = QBCore.Functions.GetPlayer(src)
    local blackmoney = exports['qb-inventory']:GetItemByName(src, "blackmoney")
    if blackmoney.amount >= data.price then
        local amount = 1
        Player.Functions.RemoveItem('blackmoney', data.price)
        TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items[data.item], "remove", data.price)
        Player.Functions.AddItem(data.item, amount)
        TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items[data.item], "add", amount)
    else
        TriggerClientEvent('QBCore:Notify', src, "You Don't Have Enough money", 'error')
    end
end)
```

to use 
```lua
TriggerEvent('mh-cashasitem:server:buyitem', cd)
```
in all your script where you use this item and it sute work fine..

**Comment by Arkosee** [comment]
So I've made a video showing as best I could what I mean.

There's nothing wrong with any script currently, outside of how it acts from the inventory perspective.. You'll see it doesn't drop properly, or save etc.. I believe that all comes down to the initial events that are not in the inventory script 
[Video](https://youtu.be/q7NLBJUGd24)


So this is one of the triggers in the inventory for normal "cash" and it works and acts fine from an inventory perspective
```lua
TriggerEvent('mh-cashasitem:server:updateCash', src, fromItemData, fromAmount, "remove", false)
```

I assume something like this needs to be added with all the ones above so the "blackmoney" works correctly from an inventory perspective

```lua
TriggerEvent('mh-blackmoneyasitem:server:updateCash', src, fromItemData, fromAmount, "remove", false)
```

**Comment by MaDHouSe79** [comment]
[blackmoney.txt](https://github.com/MaDHouSe79/mh-inventory/files/12909044/blackmoney.txt)
 maby this wil work? if you use blackmoney in qbcore config?

```lua
QBConfig.Money.MoneyTypes = { cash = 500, bank = 5000, crypto = 0, blackmoney = 0 }
```

**Comment by MaDHouSe79** [comment]
[blackmoney.txt](https://github.com/MaDHouSe79/mh-inventory/files/12909065/blackmoney.txt)
i think this one works, i have not tested it yet ;)

**Comment by Arkosee** [comment]
> [blackmoney.txt](https://github.com/MaDHouSe79/mh-inventory/files/12909065/blackmoney.txt) i think this one works, i have not tested it yet ;)

Currently testing with another person this popped up server side atm

![Screenshot 2023-10-15 200156](https://github.com/MaDHouSe79/mh-inventory/assets/105973488/583a481e-faa4-4622-baf4-1cf9a27377ac)

**Comment by MaDHouSe79** [comment]
[blackmoney_fixed.txt](https://github.com/MaDHouSe79/mh-inventory/files/12909075/blackmoney_fixed.txt)
and this one?

**Comment by Arkosee** [comment]
New error 

![Screenshot 2023-10-15 200617](https://github.com/MaDHouSe79/mh-inventory/assets/105973488/8a76a049-208d-4f05-a6b3-c55e2fb56e06)

**Comment by MaDHouSe79** [comment]
i see i have to change some things, i get back to it ok?

**Comment by MaDHouSe79** [comment]
![buywithblackmoney](https://github.com/MaDHouSe79/mh-inventory/assets/15558440/450fecf7-095e-4663-bce9-924091a88361)
this sute work fine i think ;)

**Comment by MaDHouSe79** [comment]
i just update the mh-cashasitem and the mh-inventory see if it works for you

**Comment by Arkosee** [comment]
![Screenshot 2023-10-15 221503](https://github.com/MaDHouSe79/mh-inventory/assets/105973488/78cc2df7-9902-4e50-803b-a9e9b54df369)
Still having the issue where it doesn't work properly with the inventory like in the video I posted earlier.. Other than that, it seems to be working well

**Comment by MaDHouSe79** [comment]
i can drop and take it with no issues?

**Comment by MaDHouSe79** [comment]
did you download a new inventory and cash asitem? i also put a mh-blackmarket on my git that works with the inventory

**Comment by Arkosee** [comment]
Yeah I downloaded both, it seems when I open and close the inventory my "cash" duplicates and adds to itself

**Comment by MaDHouSe79** [comment]
ok take the cashasitem server file and see i f it still duplicates

**Comment by Arkosee** [comment]
Nice, it fixed the duping, Now also when you move it to the dropped inventory, it drops, but it stays in the player one as 0.0 when you open it next time

![Screenshot 2023-10-15 223040](https://github.com/MaDHouSe79/mh-inventory/assets/105973488/5b695ca2-a19c-43fc-9f82-18e9ee818475)

**Comment by Arkosee** [comment]
![Screenshot 2023-10-15 223352](https://github.com/MaDHouSe79/mh-inventory/assets/105973488/7bd77613-382c-4757-8d2f-3d18a964ae76)
I just tried to pull money out of the bank to see what happened

**Comment by MaDHouSe79** [comment]
Ok downloas the scripts again an see if it now works

**Comment by MaDHouSe79** [comment]
i think you need to dowload it again cause i just update it, and it works now ;)

**Comment by Arkosee** [comment]
> i think you need to dowload it again cause i just update it, and it works now ;)

Sorry just woke up xD... I've updated both this happens to the inventory when opening it to pickup dropped items;
![Screenshot 2023-10-16 065615](https://github.com/MaDHouSe79/mh-inventory/assets/105973488/731cb33f-97fc-477c-b5fd-c5b5c5c7f18b)

This is the error relating to the blank drop side;

![Screenshot 2023-10-16 065908](https://github.com/MaDHouSe79/mh-inventory/assets/105973488/43e498c2-8c98-47d0-b5d5-25c686369f49)


After getting the "blank" drop side you have to close the inventory and re-open it to fix it then get this error when pulling things from the "drop" side of the inventory and the bag remains on ground

![Screenshot 2023-10-16 065733](https://github.com/MaDHouSe79/mh-inventory/assets/105973488/76b0ac6b-28eb-456c-8569-2e30a2097782)
