### ISSUE TITLE
All inventory item deleted after relog

### ISSUE THREAD

**Issue by Hexney272** [MaDHouSe79/mh-inventory#6]
Every item deleted in the inventory execpt the Cash item after relog.

**Comment by Hexney272** [comment]
I just plug your inventory to my server, added the SQL in the database. Doesnt have any error. Every player lose the inventory items after the relog. Only the Cash item have inside the inventory.

**Comment by MaDHouSe79** [comment]
Where do you see that you have to add a database?

**Comment by Hexney272** [comment]
> Where do you see that you have to add a database?

I dont see anywhere. I dont know what is the problem and how to fix

**Comment by MaDHouSe79** [comment]
you said "I just plug your inventory to my server, added the SQL in the database. Doesnt have any error."

so i ask you, Where do you see that you have to add a database?

**Comment by Hexney272** [comment]
Okay i understand but i dont think this is the problem.

**Comment by MaDHouSe79** [comment]
i don't have discord sorry.
