### ISSUE TITLE
Max Item capacity 

### ISSUE THREAD

**Issue by CollapsedLegacy** [MaDHouSe79/mh-inventory#7]
Hi guys, Just checking if it's possible to have a certain item e.g. steel to have a max threshold of 200 per stack. E.g. I have 399 steel which would normally go into one slot but I want the items max capacity to be 200 so there'd be 1 slot with 200 and 1 with 199.

**Comment by MaDHouSe79** [comment]
Hi, this is not my inventory but ps-inventory, if you want this you have to ask here: https://github.com/Project-Sloth/ps-inventory

i only make this to work with mh-cashasitem, if there is an update of ps then i update this one to.
